#!/usr/bin/env python3
"""Sync ~/.claude/copilot-globals.md into each subscribed repo's
.github/instructions/globals.instructions.md.

Background: GitHub Copilot's PR review bot reads `.github/copilot-instructions.md`
plus any `.github/instructions/*.instructions.md` files (with applyTo glob support
and excludeAgent opt-out). Each file has roughly a 4,000-char silent-truncation
cap. Joe's user-level globals previously had to be restated in every project's
copilot-instructions.md, pushing several past the cap. This script hoists the
globals into a path-scoped instructions file maintained in one place.

Usage:
    sync-copilot-globals.py [--source PATH] [--targets PATH] [--dry-run]
                            [--only NAME[,NAME...]] [REPO ...]

If REPO arguments are given, they override the targets file.
Default source: ~/.claude/copilot-globals.md
Default targets file: tools/scripts/sync-targets.txt (sibling to this script).

Exit codes:
    0  all targets updated (or unchanged)
    1  one or more targets failed
"""

import argparse
import sys
from pathlib import Path

DEFAULT_SOURCE = Path.home() / ".claude" / "copilot-globals.md"
DEFAULT_TARGETS_FILE = Path(__file__).resolve().parent / "sync-targets.txt"
GENERATED_HEADER = (
    "<!-- Generated by tools/scripts/sync-copilot-globals.py "
    "from ~/.claude/copilot-globals.md. Edit the source, then re-run the script. -->"
)


def load_targets(targets_file: Path) -> list[Path]:
    if not targets_file.exists():
        return []
    out = []
    for raw in targets_file.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        out.append(Path(line).expanduser())
    return out


def render_output(source_text: str) -> str:
    """Insert the generated-header marker after the YAML frontmatter."""
    if source_text.startswith("---\n"):
        end = source_text.find("\n---\n", 4)
        if end != -1:
            frontmatter = source_text[: end + 5]
            body = source_text[end + 5 :].lstrip("\n")
            return f"{frontmatter}\n{GENERATED_HEADER}\n\n{body}"
    return f"{GENERATED_HEADER}\n\n{source_text}"


def sync_to(repo: Path, content: str, dry_run: bool) -> str:
    target = repo / ".github" / "instructions" / "globals.instructions.md"
    existing = target.read_text() if target.exists() else None
    if existing == content:
        return f"unchanged: {target}"
    verb_prefix = "would " if dry_run else ""
    verb = "create" if existing is None else "update"
    if dry_run:
        return f"{verb_prefix}{verb}: {target}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return f"{verb}d: {target}"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                        help=f"Source file (default: {DEFAULT_SOURCE})")
    parser.add_argument("--targets", type=Path, default=DEFAULT_TARGETS_FILE,
                        help=f"Targets list file (default: {DEFAULT_TARGETS_FILE})")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would change without writing")
    parser.add_argument("--only", default="",
                        help="Comma-separated repo names to filter the targets list")
    parser.add_argument("repos", nargs="*", type=Path,
                        help="Repo paths (overrides the targets file)")
    args = parser.parse_args()

    if not args.source.exists():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 1

    content = render_output(args.source.read_text())

    repos = args.repos or load_targets(args.targets)
    if not repos:
        print(
            f"error: no target repos given and {args.targets} is empty or missing",
            file=sys.stderr,
        )
        return 1

    if args.only:
        only = {n.strip() for n in args.only.split(",") if n.strip()}
        repos = [r for r in repos if r.name in only]
        if not repos:
            print(f"error: --only {args.only} matched no targets", file=sys.stderr)
            return 1

    failed = 0
    for repo in repos:
        if not (repo / ".git").is_dir():
            print(f"skip: not a git repo: {repo}", file=sys.stderr)
            failed += 1
            continue
        try:
            print(sync_to(repo, content, dry_run=args.dry_run))
        except OSError as exc:
            print(f"error: {repo}: {exc}", file=sys.stderr)
            failed += 1

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
